# ═══════════════════════════════════════════════════════════════════
# AlmostFinishedBot - Deployment Script v2.0
# ═══════════════════════════════════════════════════════════════════
# Run with:
#   Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
#   & "$env:USERPROFILE\Downloads\Deploy_AlmostFinishedBot.ps1"
#
# This script copies ALL files from the source folder to the bot
# directory and MT5, verifies integrity, and installs packages.
# ═══════════════════════════════════════════════════════════════════

param(
    [string]$SourceDir = "",
    [switch]$SkipPackages,
    [switch]$Force
)

# ── Configuration ─────────────────────────────────────────────────
$BotDir    = "$env:USERPROFILE\Desktop\AlmostFinishedBot"
$MT5Base   = "$env:APPDATA\MetaQuotes\Terminal\73B7A2420D6397DFF9014A20F1201F97"
$MT5MQL    = "$MT5Base\MQL5"
$MT5Expert = "$MT5MQL\Experts"
$MT5Files  = "$MT5MQL\Files\AlmostFinishedBot"
$MT5Logs   = "$MT5MQL\Logs"
$ExportsDir= "$BotDir\exports"

# ── Theme colours for output ──────────────────────────────────────
function Write-Header($text) { Write-Host "`n  $text" -ForegroundColor Cyan }
function Write-OK($text)     { Write-Host "  [OK]   $text" -ForegroundColor Green }
function Write-WARN($text)   { Write-Host "  [WARN] $text" -ForegroundColor Yellow }
function Write-ERR($text)    { Write-Host "  [ERR]  $text" -ForegroundColor Red }
function Write-INFO($text)   { Write-Host "  [INFO] $text" -ForegroundColor Gray }

# ═══════════════════════════════════════════════════════════════════
# Banner
# ═══════════════════════════════════════════════════════════════════
Clear-Host
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════════════╗" -ForegroundColor Red
Write-Host "  ║    ALMOSTFINISHEDBOT  —  DEPLOYMENT SCRIPT v2.0      ║" -ForegroundColor Red
Write-Host "  ║    Gold Trading Bot | MT5 + Python + ML Ensemble     ║" -ForegroundColor DarkGray
Write-Host "  ╚═══════════════════════════════════════════════════════╝" -ForegroundColor Red
Write-Host ""

# ═══════════════════════════════════════════════════════════════════
# Step 1: Locate source files
# ═══════════════════════════════════════════════════════════════════
Write-Header "STEP 1: Locating source files"

if ($SourceDir -eq "") {
    # Auto-detect: look in Downloads, Desktop, and current directory
    $searchPaths = @(
        $PSScriptRoot,
        "$env:USERPROFILE\Downloads",
        "$env:USERPROFILE\Desktop",
        (Get-Location).Path
    )
    foreach ($p in $searchPaths) {
        if (Test-Path "$p\AlmostFinishedBot_ControlCenter.py") {
            $SourceDir = $p
            break
        }
        # Check if files are loose in the folder alongside the script
        if (Test-Path "$p\risk_manager.py") {
            $SourceDir = $p
            break
        }
    }
}

if ($SourceDir -eq "" -or !(Test-Path $SourceDir)) {
    Write-ERR "Cannot find source files automatically."
    Write-Host ""
    Write-Host "  Place all bot files in the same folder as this script," -ForegroundColor Yellow
    Write-Host "  or specify the path:" -ForegroundColor Yellow
    Write-Host "    .\Deploy_AlmostFinishedBot.ps1 -SourceDir 'C:\path\to\files'" -ForegroundColor White
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit 1
}

Write-OK "Source directory: $SourceDir"

# ═══════════════════════════════════════════════════════════════════
# Step 2: Define all expected files
# ═══════════════════════════════════════════════════════════════════
Write-Header "STEP 2: Checking source files"

# Core Python scripts
$PythonScripts = @(
    "AlmostFinishedBot_ControlCenter.py",
    "risk_manager.py",
    "train_models.py",
    "market_regime.py",
    "news_guard.py",
    "news_sentiment.py",
    "correlation_guard.py",
    "smc_detector.py",
    "live_graph.py",
    "trade_monitor.py"
)

# MT5 EA file
$EAFiles = @(
    "AlmostFinishedBot_EA.mq5"
)

# JSON configs (will be created with defaults if missing)
$JsonConfigs = @(
    "bot_settings.json",
    "ensemble_config.json",
    "current_signal.json",
    "regime_cache.json",
    "news_cache.json",
    "smc_cache.json",
    "risk_status.json"
)

# ML model files (optional — generated by training)
$ModelFiles = @(
    "xgb_model.pkl",
    "lgb_model.pkl",
    "gb_model.pkl",
    "scaler.pkl",
    "ensemble.pkl",
    "lstm_model.keras"
)

# Other files
$OtherFiles = @(
    "Launch_ControlCenter.bat"
)

# Files to EXCLUDE (legacy IBKR_GoldBot files)
$ExcludeFiles = @(
    "gold_bot.py",
    "ml_retrainer_gui.py",
    "performance_charts.py",
    "train_ultragold_ml.py",
    "ultragold_analytics.py",
    "ultragold_dashboard.py",
    "ultragold_dashboard.html",
    "gold_training_data.csv",
    "UltraGold_MultiSymbol_EA.mq5",
    "UltraGold_MultiSymbol_EA.ex5",
    "rf_model.pkl",
    "nn_model.h5",
    "AlmostFinishedBot_SETUP.ps1"
)

# Check which source files exist
$found = 0; $missing = 0
foreach ($f in $PythonScripts) {
    if (Test-Path "$SourceDir\$f") { Write-OK $f; $found++ }
    else { Write-ERR "MISSING: $f (REQUIRED)"; $missing++ }
}
foreach ($f in $EAFiles) {
    if (Test-Path "$SourceDir\$f") { Write-OK $f; $found++ }
    else { Write-WARN "MISSING: $f (EA won't update in MT5)"; $missing++ }
}
foreach ($f in $JsonConfigs) {
    if (Test-Path "$SourceDir\$f") { Write-OK $f; $found++ }
    else { Write-INFO "MISSING: $f (will create default)" }
}
foreach ($f in $ModelFiles) {
    if (Test-Path "$SourceDir\$f") { Write-OK "$f (trained model)"; $found++ }
    else { Write-INFO "$f not found (retrain via Control Center)" }
}
foreach ($f in $OtherFiles) {
    if (Test-Path "$SourceDir\$f") { Write-OK $f; $found++ }
}

Write-Host ""
Write-INFO "Found $found files | Missing required: $missing"

if ($missing -gt 0 -and !$Force) {
    Write-Host ""
    Write-WARN "Some required files are missing. Use -Force to deploy anyway."
    $confirm = Read-Host "  Continue anyway? (y/N)"
    if ($confirm -ne "y" -and $confirm -ne "Y") { exit 1 }
}

# ═══════════════════════════════════════════════════════════════════
# Step 3: Create directories
# ═══════════════════════════════════════════════════════════════════
Write-Header "STEP 3: Creating directories"

$dirs = @($BotDir, $ExportsDir)
if (Test-Path $MT5Base) {
    $dirs += @($MT5Expert, $MT5Files)
}

foreach ($d in $dirs) {
    New-Item -ItemType Directory -Force -Path $d | Out-Null
    Write-OK $d
}

if (!(Test-Path $MT5Base)) {
    Write-WARN "MT5 terminal not found at expected path"
    Write-WARN "EA and signal files will NOT be copied to MT5"
    Write-WARN "Expected: $MT5Base"
}

# ═══════════════════════════════════════════════════════════════════
# Step 4: Backup existing files
# ═══════════════════════════════════════════════════════════════════
Write-Header "STEP 4: Backing up existing files"

$backupDir = "$BotDir\_backup_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
$existingFiles = Get-ChildItem -Path $BotDir -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -ne "_backup_*" -and $_.Extension -in ".py",".mq5",".json",".bat",".pkl",".keras" }

if ($existingFiles.Count -gt 0) {
    New-Item -ItemType Directory -Force -Path $backupDir | Out-Null
    foreach ($ef in $existingFiles) {
        Copy-Item $ef.FullName "$backupDir\$($ef.Name)" -Force
    }
    Write-OK "Backed up $($existingFiles.Count) files to $backupDir"
} else {
    Write-INFO "No existing files to backup (fresh install)"
}

# ═══════════════════════════════════════════════════════════════════
# Step 5: Copy files to bot directory
# ═══════════════════════════════════════════════════════════════════
Write-Header "STEP 5: Deploying files to $BotDir"

$copied = 0
$allBotFiles = $PythonScripts + $JsonConfigs + $ModelFiles + $OtherFiles

foreach ($f in $allBotFiles) {
    $src = "$SourceDir\$f"
    $dst = "$BotDir\$f"
    if (Test-Path $src) {
        Copy-Item $src $dst -Force
        Write-OK "Copied: $f"
        $copied++
    }
}

# Create default JSON configs if they don't exist
$defaults = @{
    "bot_settings.json" = @'
{
  "mode": "normal",
  "base_risk_pct": 1.0,
  "god_mode_max_risk": 8.0,
  "god_mode_threshold": 0.88,
  "prop_firm_mode": false,
  "prop_daily_dd_limit": 3.0,
  "prop_total_dd_limit": 6.0,
  "prop_profit_target": 8.0,
  "equity_halve_trigger": 5.0,
  "equity_restore_pct": 20.0,
  "vol_target_pct": 1.0,
  "compound_auto": true,
  "starting_balance": 100.0,
  "current_balance": 100.0,
  "peak_balance": 100.0
}
'@
    "current_signal.json" = '{"signal":"NEUTRAL","confidence":0.5,"kelly_fraction":0.01,"risk_multiplier":0.5,"sized_risk_pct":0.5,"timestamp":"1970-01-01 00:00:00"}'
    "news_cache.json" = '{"signal":"NEUTRAL","score":0.0,"articles_analysed":0,"top_articles":[],"timestamp":"1970-01-01T00:00:00"}'
    "regime_cache.json" = '{"regime":"UNKNOWN","adx":0,"bbw":0,"hurst":0.5,"volume_bias":0,"risk_mult":0.1,"allows_long":false,"allows_short":false,"timestamp":"1970-01-01 00:00:00"}'
    "smc_cache.json" = '{"signal":0,"score":0,"reasons":["Not scanned yet"],"timestamp":"1970-01-01 00:00:00"}'
    "risk_status.json" = '{"risk_pct":0,"mode":"NORMAL","god_mode":false,"trade_allowed":false,"session":"UNKNOWN","timestamp":"1970-01-01 00:00:00"}'
}

foreach ($fname in $defaults.Keys) {
    $fpath = "$BotDir\$fname"
    if (!(Test-Path $fpath)) {
        Set-Content -Path $fpath -Value $defaults[$fname] -Encoding UTF8
        Write-INFO "Created default: $fname"
    }
}

# Ensure Launch_ControlCenter.bat exists
$batPath = "$BotDir\Launch_ControlCenter.bat"
if (!(Test-Path $batPath)) {
    $batContent = @"
@echo off
title AlmostFinishedBot Control Center
cd /d "%USERPROFILE%\Desktop\AlmostFinishedBot"
python AlmostFinishedBot_ControlCenter.py
pause
"@
    Set-Content -Path $batPath -Value $batContent -Encoding ASCII
    Write-INFO "Created: Launch_ControlCenter.bat"
}

Write-Host ""
Write-OK "Deployed $copied files to bot directory"

# ═══════════════════════════════════════════════════════════════════
# Step 6: Deploy EA to MT5
# ═══════════════════════════════════════════════════════════════════
Write-Header "STEP 6: Deploying to MetaTrader 5"

if (Test-Path $MT5Base) {
    # Copy EA to Experts folder
    $eaSrc = "$SourceDir\AlmostFinishedBot_EA.mq5"
    if (Test-Path $eaSrc) {
        Copy-Item $eaSrc "$MT5Expert\AlmostFinishedBot_EA.mq5" -Force
        Write-OK "EA copied to: $MT5Expert"
    } else {
        Write-WARN "EA source file not found — skipping"
    }

    # Copy signal files to MT5 Files directory (EA reads from here)
    $signalFiles = @("current_signal.json", "regime_cache.json", "news_cache.json",
                     "smc_cache.json", "news_guard.json", "correlation_status.json",
                     "bot_settings.json")

    foreach ($sf in $signalFiles) {
        $sfSrc = "$BotDir\$sf"
        if (Test-Path $sfSrc) {
            Copy-Item $sfSrc "$MT5Files\$sf" -Force
        }
    }
    Write-OK "Signal files synced to: $MT5Files"

    # Create a signal-sync script so Python scripts can push updates to MT5
    $syncScript = @'
"""
AlmostFinishedBot - Signal Sync
Copies signal files from bot directory to MT5 Files directory.
Run this as a background process to keep MT5 in sync.
"""
import os, shutil, time

BOT_DIR  = os.path.join(os.path.expanduser("~"), "Desktop", "AlmostFinishedBot")
MT5_DIR  = os.path.join(os.environ.get("APPDATA",""), "MetaQuotes", "Terminal",
           "73B7A2420D6397DFF9014A20F1201F97", "MQL5", "Files", "AlmostFinishedBot")

SYNC_FILES = ["current_signal.json", "regime_cache.json", "news_cache.json",
              "smc_cache.json", "news_guard.json", "correlation_status.json",
              "bot_settings.json", "risk_status.json"]

os.makedirs(MT5_DIR, exist_ok=True)
print(f"Syncing: {BOT_DIR} -> {MT5_DIR}")
print(f"Files: {', '.join(SYNC_FILES)}")
print("Press Ctrl+C to stop\n")

while True:
    for f in SYNC_FILES:
        src = os.path.join(BOT_DIR, f)
        dst = os.path.join(MT5_DIR, f)
        try:
            if os.path.exists(src):
                src_mtime = os.path.getmtime(src)
                dst_mtime = os.path.getmtime(dst) if os.path.exists(dst) else 0
                if src_mtime > dst_mtime:
                    shutil.copy2(src, dst)
        except Exception:
            pass
    time.sleep(2)
'@
    Set-Content -Path "$BotDir\signal_sync.py" -Value $syncScript -Encoding UTF8
    Write-OK "Created signal_sync.py (keeps MT5 signal files in sync)"

} else {
    Write-WARN "MT5 not found — skipping MT5 deployment"
    Write-INFO "Install MT5 and re-run this script to deploy the EA"
}

# ═══════════════════════════════════════════════════════════════════
# Step 7: Install Python packages
# ═══════════════════════════════════════════════════════════════════
Write-Header "STEP 7: Python environment check"

$pythonOK = $false
try {
    $pyVer = & python --version 2>&1
    Write-OK "Python found: $pyVer"
    $pythonOK = $true
} catch {
    Write-ERR "Python not found in PATH"
    Write-WARN "Install Python 3.9+ from python.org and add to PATH"
}

if ($pythonOK -and !$SkipPackages) {
    Write-INFO "Installing required packages (this may take a few minutes)..."

    $packages = @(
        "numpy",
        "pandas",
        "scikit-learn",
        "xgboost",
        "lightgbm",
        "yfinance",
        "joblib",
        "feedparser",
        "vaderSentiment",
        "requests",
        "matplotlib"
    )

    $optionalPackages = @(
        "tensorflow"
    )

    foreach ($pkg in $packages) {
        Write-Host "  Installing $pkg..." -NoNewline -ForegroundColor Gray
        $result = & python -m pip install $pkg -q 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host " OK" -ForegroundColor Green
        } else {
            Write-Host " FAILED" -ForegroundColor Red
        }
    }

    Write-Host ""
    Write-INFO "Optional packages (LSTM support):"
    foreach ($pkg in $optionalPackages) {
        Write-Host "  Installing $pkg..." -NoNewline -ForegroundColor Gray
        $result = & python -m pip install $pkg -q 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host " OK" -ForegroundColor Green
        } else {
            Write-Host " SKIP (bot works without it)" -ForegroundColor Yellow
        }
    }
} elseif ($SkipPackages) {
    Write-INFO "Package installation skipped (-SkipPackages flag)"
}

# ═══════════════════════════════════════════════════════════════════
# Step 8: Verification
# ═══════════════════════════════════════════════════════════════════
Write-Header "STEP 8: Verification"

$pass = 0; $fail = 0; $warn = 0

# Check core scripts
foreach ($f in $PythonScripts) {
    if (Test-Path "$BotDir\$f") {
        $sz = (Get-Item "$BotDir\$f").Length
        if ($sz -gt 100) { $pass++ } else { Write-WARN "$f is suspiciously small ($sz bytes)"; $warn++ }
    } else { Write-ERR "$f NOT deployed"; $fail++ }
}

# Check EA in MT5
if (Test-Path $MT5Base) {
    if (Test-Path "$MT5Expert\AlmostFinishedBot_EA.mq5") {
        Write-OK "EA deployed to MT5 Experts"
        $pass++
    } else {
        Write-WARN "EA not in MT5 Experts folder"
        $warn++
    }

    if (Test-Path $MT5Files) {
        Write-OK "MT5 Files/AlmostFinishedBot directory exists"
        $pass++
    }
}

# Check models
$modelCount = 0
foreach ($f in $ModelFiles) {
    if (Test-Path "$BotDir\$f") { $modelCount++ }
}
if ($modelCount -ge 4) {
    Write-OK "ML models present ($modelCount/6)"
} elseif ($modelCount -gt 0) {
    Write-WARN "Only $modelCount/6 models found — retrain recommended"
    $warn++
} else {
    Write-INFO "No ML models — train via Control Center first"
}

# Check JSON configs
foreach ($f in $JsonConfigs) {
    if (Test-Path "$BotDir\$f") { $pass++ }
    else { Write-ERR "$f missing"; $fail++ }
}

Write-Host ""

# ═══════════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════════
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║              DEPLOYMENT COMPLETE                     ║" -ForegroundColor Cyan
Write-Host "  ╚═══════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Bot Directory : $BotDir" -ForegroundColor White
if (Test-Path $MT5Base) {
    Write-Host "  MT5 Experts   : $MT5Expert" -ForegroundColor White
    Write-Host "  MT5 Files     : $MT5Files" -ForegroundColor White
}
if ($existingFiles.Count -gt 0) {
    Write-Host "  Backup        : $backupDir" -ForegroundColor DarkGray
}
Write-Host ""
Write-Host "  Results: " -NoNewline
Write-Host "$pass passed" -NoNewline -ForegroundColor Green
Write-Host " | " -NoNewline
Write-Host "$warn warnings" -NoNewline -ForegroundColor Yellow
Write-Host " | " -NoNewline
Write-Host "$fail failed" -ForegroundColor $(if ($fail -gt 0) { "Red" } else { "Green" })
Write-Host ""
Write-Host "  ─────────────────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host "  NEXT STEPS:" -ForegroundColor Yellow
Write-Host "    1. Double-click Launch_ControlCenter.bat" -ForegroundColor White
Write-Host "    2. Click 'Train All Models' (Training section)" -ForegroundColor White
Write-Host "    3. Click 'System Health Check' to verify" -ForegroundColor White
Write-Host "    4. Open MT5, compile EA, attach to XAUUSD chart" -ForegroundColor White
Write-Host "    5. Start Paper Trading first!" -ForegroundColor White
Write-Host "  ─────────────────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host ""

# Open the bot folder
Start-Process explorer.exe $BotDir

Write-Host "  Press any key to exit..." -ForegroundColor DarkGray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
